def generate_step(file, step)
  return unless step.complete?

  comment = "Step #{step.order}: #{helpers.escape_javascript get_comment(step)}"
  file.puts "\n/* #{comment} */"

  case step.action_type
    when 'pageload'
      file.puts "driver.get('#{helpers.escape_javascript step.webpage}');"
    when 'scroll'
      file.puts "driver.executeScript('scroll(#{step.scrollLeft}, #{step.scrollTop})');"
    when 'keypress'
      file.puts "driver.action().sendKeys('#{helpers.escape_javascript step.typed}').perform();"
    when 'resize'
      file.puts "driver.manage().window.setSize(new Dimension(#{step.screenwidth}, #{step.screenheight}));"
    when 'click'
      type = step.selector[:selectorType]
      selector = helpers.escape_javascript step.selector[:selector].strip
      eq = step.selector[:eq].to_i
      case type # first, find DOM with WebDriver
        when 'id'
          file.puts "driver.findElement(By.id('#{selector}'));"
        when 'class'
          if selector.include? ' '
            selector = ".#{selector.split.join('.')}"
            file.puts "driver.findElements(By.cssSelector('#{selector}'))[#{eq}];"
          else # 1 single class
            file.puts "driver.findElements(By.className('#{selector}'))[#{eq}];"
          end
        when 'tag'
          file.puts "driver.findElements(By.tagName('#{selector}'))[#{eq}];"
        when 'name'
          file.puts "driver.findElements(By.name => '#{selector}')[#{eq}];"
        when 'partialLink' # link text
          file.puts "driver.findElements(By.partialLinkText('#{selector}'))[#{eq}];"
        when 'href'
          file.puts "driver.findElements(By.cssSelector(\"a[href='#{selector}']\"))[#{eq}];"
        when 'partialHref'
          file.puts "driver.findElements(By.cssSelector(\"a[href*='#{selector}']\"))[#{eq}];"
        when 'button' # use XPath
          file.puts "driver.findElements(By.:xpath, \"//button[text()[contains(.,'#{selector}')]]\")[#{eq}]"
        when 'css'
          if eq > 0
            file.puts "driver.findElements(By.cssSelector('#{selector}'))[#{eq}];"
          else
            file.puts "driver.findElement(By.cssSelector('#{selector}'));"
          end
        when 'coordination'
          file.puts "elem = driver.find_elements(By.tagName('body'))[0];"
          file.puts "driver.action().moveToElement(elem, #{step.selector[:x]}, #{step.selector[:y]}).click().perform();"
        else
          nil
      end
    else
      true
  end
end

title = "Generated by UIChecks.com
Test title: #{test.title}
Language: #{language.capitalize}"

file.puts "/*
#{title}
*/\n"

file.puts "import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.WebDriverWait;

public class AutoTesting {
  public static void main(String[] args) {
    System.setProperty(\"webdriver.chrome.driver\", \"/Path/chromedriver\");
    WebDriver driver = new ChromeDriver();\n\n"

first_step = Step.where(test: @test).first
file.puts "driver.manage.window.resize_to(#{first_step.screenwidth}, #{first_step.screenheight})" if first_step.screenwidth

@test.steps.each { |step|
  generate_step(file, step)
}

file.puts ' }
}'



